version: '3.8'

services:
  secretforge-ui:
    image: "ghcr.io/mrgarbonzo/secretforge/ui:latest"
    container_name: "secretforge-ui"
    ports:
      - "80:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
